### ISSUE TITLE
Ошибка при запросе

### ISSUE THREAD

**Issue by mirecl** [Temik26/sber-tech-task#2]
Запустил Docker и выполнил запрос - получил 500 ошибку:
```sh
[03/Aug/2022 06:44:56] "POST /api/v1/deposit/deposit_calculation HTTP/1.1" 500 59705

Performing system checks...


System check identified no issues (0 silenced).


You have 19 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, deposit_account, sessions.

Run 'python manage.py migrate' to apply them.

August 03, 2022 - 06:43:32

Django version 4.0.6, using settings 'deposit.settings'

Starting development server at http://0.0.0.0:8000/

Quit the server with CONTROL-C.

Internal Server Error: /api/v1/deposit/deposit_calculation/

Traceback (most recent call last):

  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute

    return self.cursor.execute(sql, params)

  File "/usr/local/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 477, in execute

    return Database.Cursor.execute(self, query, params)

sqlite3.OperationalError: no such table: deposit_account_deposit
```

**Comment by Temik26** [comment]
Добавил команду для проведения миграций
